### ISSUE TITLE
Incorrect information for Frontend NE

### ISSUE THREAD

**Issue by htmlandbacon** [AverageMarcus/funded-meetups#1]
Current information:

Frontend NE is a monthly meetup and yearly conference about frontend development.

Expected Information:

Frontend NE is a monthly meet-up  about frontend development in Newcastle.

For our conference we cover full accommodation/travel and pay speakers.

**Comment by AverageMarcus** [comment]
Thanks! Just made this change. It'll be pushed out shortly.
